# ── Constants ───────────────────────────────────────────────────────────────
set -g pane-base-index 1

# ── Plugins (TPM) ───────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TPM. MUST be the very last line.
run '~/.tmux/plugins/tpm/tpm'
